// build script - writes index.html
const fs = require('fs');
const p = 'e:/\u817e\u8bafpcg/prototype/index.html';
const lines = [];
const add = s => lines.push(s);
add('<!DOCTYPE html>');
add('<html lang="zh-CN">');
add('<head>');
add('  <meta charset="UTF-8">');
add('  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">');
add('  <title>\u817e\u8bafAI \u00b7 QQ\u97f3\u4e50 \u00d7 \u817e\u8baf\u89c6\u9891 \u00d7 AI\u6821\u56ed\u6d3b\u52a8\u7b56\u5212\u52a9\u624b</title>');
add('  <link rel="stylesheet" href="css/style.css">');
add('  <link rel="preconnect" href="https://fonts.googleapis.com">');
add('  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap" rel="stylesheet">');
add('</head>');
add('<body>');
add('  <!-- Page 1: \u9996\u9875/\u8f93\u5165\u9875 -->');
add('  <div id="page-input" class="page active">');
add('    <header class="header">');
add('      <div class="logo">');
add('        <span class="logo-icon">\ud83c\udfb5</span>');
add('        <span class="logo-text">\u817e\u8baf<span class="highlight">AI</span></span>');
add('      </div>');
add('      <span class="logo-subtitle">QQ\u97f3\u4e50 \u00d7 \u817e\u8baf\u89c6\u9891 \u00d7 AI\u6821\u56ed\u6d3b\u52a8\u7b56\u5212\u52a9\u624b</span>');
add('    </header>');
add('    <section class="slogan">');
add('      <h1>\u300c10\u5206\u949f\uff0c\u7b56\u5212\u4e00\u573a\u4e13\u4e1a\u7ea7\u6821\u56ed\u6d3b\u52a8\u300d</h1>');
add('    </section>');
add('    <main class="form-container">');
add('      <div class="form-card">');
add('        <div class="form-group">');
add('          <label class="form-label"><span class="label-num">\u2460</span>\u6d3b\u52a8\u4e3b\u9898</label>');
add('          <textarea id="theme" class="form-input form-textarea" rows="2" placeholder="\u4f8b\u5982\uff1a\u52a8\u6f2b\u793e\u8fce\u65b0\u665a\u4f1a&#10;\u53ef\u4ee5\u5199\u66f4\u591a\u80cc\u666f\u8bf4\u660e..."></textarea>');
add('        </div>');
add('        <div class="form-group">');
add('          <label class="form-label"><span class="label-num">\u2461</span>\u9884\u8ba1\u4eba\u6570</label>');
add('          <div class="chip-group" id="people-group">');
add('            <button class="chip" data-value="5">5\u4eba</button>');
add('            <button class="chip" data-value="10">10\u4eba</button>');
add('            <button class="chip active" data-value="20">20\u4eba</button>');
add('            <button class="chip" data-value="50">50\u4eba</button>');
add('            <button class="chip" data-value="100">100\u4eba\u4ee5\u4e0a</button>');
add('          </div>');
add('        </div>');
add('        <div class="form-group">');
add('          <label class="form-label"><span class="label-num">\u2462</span>\u6d3b\u52a8\u65f6\u957f</label>');
add('          <div class="chip-group" id="duration-group">');
add('            <button class="chip" data-value="60">1\u5c0f\u65f6</button>');
add('            <button class="chip" data-value="120">2\u5c0f\u65f6</button>');
add('            <button class="chip active" data-value="180">3\u5c0f\u65f6</button>');
add('            <button class="chip" data-value="240">\u534a\u5929</button>');
add('          </div>');
add('        </div>');
add('        <div class="form-group">');
add('          <label class="form-label"><span class="label-num">\u2463</span>\u6d3b\u52a8\u98ce\u683c <span class="label-hint">\u53ef\u591a\u9009</span></label>');
add('          <div class="tag-group" id="style-group">');
add('            <button class="tag" data-value="\u6b63\u5f0f">\ud83c\udfd7\ufe0f \u6b63\u5f0f</button>');
add('            <button class="tag active" data-value="\u6d3b\u6cfc">\ud83c\udf89 \u6d3b\u6cfc</button>');
add('            <button class="tag" data-value="\u641e\u7b11">\ud83e\udd21 \u641e\u7b11</button>');
add('            <button class="tag" data-value="\u6e29\u60c5">\ud83d\udc9d \u6e29\u60c5</button>');
add('            <button class="tag" data-value="\u71c3">\ud83d\udd25 \u71c3</button>');
add('            <button class="tag" data-value="\u6cbb\u6108">\ud83c\udf3f \u6cbb\u6108</button>');
add('            <button class="tag" data-value="\u6c89\u6d78">\ud83c\udfad \u6c89\u6d78</button>');
add('            <button class="tag" data-value="\u7085\u9177">\u26a1 \u7085\u9177</button>');
add('            <button class="tag" data-value="\u6587\u827a">\ud83c\udfa8 \u6587\u827a</button>');
add('            <button class="tag" data-value="\u677e\u5f1b">\u2601\ufe0f \u677e\u5f1b</button>');
add('          </div>');
add('        </div>');
add('        <div class="form-group">');
add('          <label class="form-label"><span class="label-num">\u2464</span>\u6d3b\u52a8\u7c7b\u578b</label>');
add('          <div class="select-container">');
add('            <select id="activity-type" class="form-select">');
add('              <option value="\u665a\u4f1a">\ud83c\udfad \u665a\u4f1a</option>');
add('              <option value="\u8fce\u65b0">\ud83d\udc4b \u8fce\u65b0</option>');
add('              <option value="\u6bd5\u4e1a">\ud83c\udf93 \u6bd5\u4e1a</option>');
add('              <option value="\u8054\u8c0a">\ud83e\udd1d \u8054\u8c0a</option>');
add('              <option value="\u793e\u56e2\u62db\u65b0">\ud83d\udce3 \u793e\u56e2\u62db\u65b0</option>');
add('              <option value="\u5176\u4ed6">\ud83d\udccc \u5176\u4ed6</option>');
add('            </select>');
add('          </div>');
add('        </div>');
add('        <div class="form-group">');
add('          <label class="form-label"><span class="label-num">\u2465</span>\u6d3b\u52a8\u65e5\u671f <span class="label-hint">\u9009\u586b</span></label>');
add('          <div class="date-picker-wrap">');
add('            <span class="date-icon">\ud83d\udcc5</span>');
add('            <input type="date" id="activity-date" class="form-input date-input">');
add('            <span class="date-clear" id="date-clear" title="\u6e05\u9664\u65e5\u671f">\u2715</span>');
add('          </div>');
add('          <div class="date-shortcuts">');
add('            <button class="date-shortcut" data-offset="0">\u4eca\u5929</button>');
add('            <button class="date-shortcut" data-offset="7">\u4e00\u5468\u540e</button>');
add('            <button class="date-shortcut" data-offset="14">\u4e24\u5468\u540e</button>');
add('            <button class="date-shortcut" data-offset="30">\u4e00\u4e2a\u6708\u540e</button>');
add('          </div>');
add('        </div>');
add('        <button id="btn-start" class="btn-primary">');
add('          <span class="btn-icon">\u2728</span>\u5f00\u59cb\u751f\u6210\u65b9\u6848');
add('        </button>');
add('        <div class="hint-text"><span class="hint-icon">\ud83d\udca1</span>\u770b\u770b\u522b\u4eba\u600e\u4e48\u7528 \u2192</div>');
add('      </div>');
add('    </main>');
add('  </div>');
add('');
add('  <!-- Page 2: Loading\u9875 -->');
add('  <div id="page-loading" class="page">');
add('    <div class="loading-container">');
add('      <div class="loading-animation">');
add('        <div class="music-wave">');
add('          <span></span><span></span><span></span><span></span><span></span>');
add('        </div>');
add('      </div>');
add('      <h2 class="loading-title">AI \u6b63\u5728\u4e3a\u60a8\u751f\u6210\u4e13\u5c5e\u65b9\u6848...</h2>');
add('      <div class="steps-container">');
add('        <div class="step" id="step-1"><div class="step-icon pending">\u23f3</div><div class="step-text">Step 1: \u6b63\u5728\u7406\u89e3\u4f60\u7684\u6d3b\u52a8\u9700\u6c42...</div></div>');
add('        <div class="step" id="step-2"><div class="step-icon pending">\u23f3</div><div class="step-text">Step 2: \u6b63\u5728\u751f\u6210\u6d3b\u52a8\u6d41\u7a0b\u6846\u67b6...</div></div>');
add('        <div class="step" id="step-3"><div class="step-icon pending">\u23f3</div><div class="step-text">Step 3: \u6b63\u5728\u4eceQQ\u97f3\u4e50\u5339\u914d\u4e13\u5c5e\u6b4c\u5355...</div></div>');
add('        <div class="step" id="step-4"><div class="step-icon pending">\u23f3</div><div class="step-text">Step 4: \u6b63\u5728\u751f\u6210\u4e3b\u6301\u4e32\u8bcd...</div></div>');
add('        <div class="step" id="step-5"><div class="step-icon pending">\u23f3</div><div class="step-text">Step 5: \u6b63\u5728\u751f\u6210\u6d3b\u52a8\u9884\u544a\u7247...</div></div>');
add('        <div class="step" id="step-6"><div class="step-icon pending">\u23f3</div><div class="step-text">Step 6: \u6574\u7406\u5b8c\u6210\uff0c\u5373\u5c06\u5448\u73b0\uff01</div></div>');
add('      </div>');
add('      <div class="loading-time">\u9884\u8ba1\u9700\u8981 <span class="time-highlight">15-30</span> \u79d2</div>');
add('    </div>');
add('  </div>');
add('');
add('  <!-- Page 3: \u65b9\u6848\u8f93\u51fa\u9875 -->');
add('  <div id="page-result" class="page">');
add('    <header class="result-header">');
add('      <button class="btn-back" id="btn-back"><span>\u2190</span> \u91cd\u65b0\u7b56\u5212</button>');
add('      <h1 class="result-title">\u6d3b\u52a8\u65b9\u6848</h1>');
add('      <button class="btn-share" id="btn-export"><span>\ud83d\udce4</span> \u5bfc\u51fa</button>');
add('    </header>');
add('    <div class="summary-card">');
add('      <h2 class="summary-title" id="result-theme">\u52a8\u6f2b\u793e\u8fce\u65b0\u665a\u4f1a</h2>');
add('      <div class="summary-tags">');
add('        <span class="summary-tag" id="result-type">\ud83c\udfad \u665a\u4f1a</span>');
add('        <span class="summary-tag" id="result-people">\ud83d\udc65 50-200\u4eba</span>');
add('        <span class="summary-tag" id="result-duration">\u23f0 2\u5c0f\u65f6</span>');
add('        <span class="summary-tag" id="result-style">\ud83c\udfa8 \u6d3b\u6cfc</span>');
add('        <span class="summary-tag" id="result-date" style="display:none">\ud83d\udcc5 \u65e5\u671f</span>');
add('      </div>');
add('    </div>');
add('    <nav class="tab-nav">');
add('      <button class="tab-btn active" data-tab="tab-process">\ud83d\udccb \u6d3b\u52a8\u6d41\u7a0b</button>');
add('      <button class="tab-btn" data-tab="tab-playlist">\ud83c\udfb5 \u4e13\u5c5e\u6b4c\u5355</button>');
add('      <button class="tab-btn" data-tab="tab-script">\ud83c\udfa4 \u4e3b\u6301\u4e32\u8bcd</button>');
add('      <button class="tab-btn" data-tab="tab-tasks">\u2705 \u4efb\u52a1\u6e05\u5355</button>');
add('    </nav>');
add('    <div class="tab-content">');
add('      <div id="tab-process" class="tab-pane active">');
add('        <div class="process-timeline" id="process-list"></div>');
add('        <!-- \u6d3b\u52a8\u9884\u544a\u7247\u751f\u6210\u5361\u7247 -->');
add('        <div class="trailer-card" id="trailer-card">');
add('          <div class="trailer-card-header">');
add('            <span class="trailer-icon">\ud83c\udfac</span>');
add('            <h3>\u6d3b\u52a8\u9884\u544a\u7247\u751f\u6210</h3>');
add('            <span class="trailer-badge">AI \u751f\u6210</span>');
add('          </div>');
add('          <div class="trailer-body">');
add('            <div class="trailer-cover" id="trailer-cover">');
add('              <div class="trailer-cover-placeholder"><span>\ud83c\uddef\ufe0f</span><p>\u9884\u544a\u5c01\u9762</p></div>');
add('            </div>');
add('            <div class="trailer-info">');
add('              <div class="trailer-row">');
add('                <span class="trailer-label">\u5c01\u9762\u98ce\u683c</span>');
add('                <div class="trailer-style-chips" id="trailer-style-chips">');
add('                  <button class="trailer-chip active" data-style="\u6d3b\u6cfc">\ud83c\udf89 \u6d3b\u6cfc</button>');
add('                  <button class="trailer-chip" data-style="\u6b63\u5f0f">\ud83c\udfd7\ufe0f \u6b63\u5f0f</button>');
add('                  <button class="trailer-chip" data-style="\u7085\u9177">\u26a1 \u7085\u9177</button>');
add('                </div>');
add('              </div>');
add('              <div class="trailer-row">');
add('                <span class="trailer-label">\u9884\u544a\u6587\u6848</span>');
add('                <div class="trailer-copy-tabs">');
add('                  <button class="copy-tab active" data-copy="\u6b63\u5f0f">\u6b63\u5f0f</button>');
add('                  <button class="copy-tab" data-copy="\u6d3b\u6cfc">\u6d3b\u6cfc</button>');
add('                  <button class="copy-tab" data-copy="\u641e\u7b11">\u641e\u7b11</button>');
add('                </div>');
add('                <div class="trailer-copy-text" id="trailer-copy-text"></div>');
add('              </div>');
add('              <div class="trailer-row trailer-bgm-row">');
add('                <span class="trailer-label">\ud83c\udfb5 \u80cc\u666f\u97f3\u4e50</span>');
add('                <span class="trailer-bgm-name" id="trailer-bgm">\u5339\u914d\u4e2d...</span>');
add('              </div>');
add('            </div>');
add('          </div>');
add('          <div class="trailer-actions">');
add('            <button class="btn-trailer-gen" id="btn-gen-trailer"><span>\u2728</span> \u751f\u6210\u9884\u544a\u7247</button>');
add('            <button class="btn-trailer-publish" id="btn-publish-trailer"><span>\ud83d\udcfa</span> \u4e00\u952e\u53d1\u5e03\u5230\u817e\u8baf\u89c6\u9891</button>');
add('            <button class="btn-trailer-share" id="btn-share-trailer"><span>\ud83d\udd17</span> \u751f\u6210\u5206\u4eab\u94fe\u63a5</button>');
add('          </div>');
add('          <div class="trailer-share-row" id="trailer-share-row" style="display:none">');
add('            <input class="trailer-link-input" id="trailer-link" readonly value="">');
add('            <button class="btn-share-qq" id="btn-share-qq-trailer">\ud83d\udcac QQ\u7fa4</button>');
add('            <button class="btn-share-wx" id="btn-share-wx-trailer">\ud83d\udc9a \u5fae\u4fe1</button>');
add('          </div>');
add('        </div>');
add('      </div>');
add('      <div id="tab-playlist" class="tab-pane">');
add('        <div class="playlist-sections" id="playlist-list"></div>');
add('        <button class="btn-secondary" id="btn-save-playlist"><span>\ud83d\udc9a</span> \u4e00\u952e\u4fdd\u5b58\u6b4c\u5355\u5230QQ\u97f3\u4e50</button>');
add('      </div>');
add('      <div id="tab-script" class="tab-pane">');
add('        <div class="script-list" id="script-list"></div>');
add('        <button class="btn-secondary" id="btn-export-script"><span>\ud83d\udcc4</span> \u5bfc\u51fa\u4e32\u8bcdWord\u6587\u6863</button>');
add('      </div>');
add('      <div id="tab-tasks" class="tab-pane">');
add('        <div class="task-list" id="task-list"></div>');
add('        <button class="btn-secondary" id="btn-send-qq"><span>\ud83d\udcac</span> \u4e00\u952e\u53d1\u9001\u5230QQ\u7fa4</button>');
add('      </div>');
add('    </div>');
add('  </div>');
add('');
add('  <!-- Page 4: \u5bfc\u51fa/\u5206\u4eab\u9875 -->');
add('  <div id="page-export" class="page">');
add('    <header class="export-header">');
add('      <button class="btn-back" id="btn-back-export"><span>\u2190</span> \u8fd4\u56de\u65b9\u6848</button>');
add('      <h1>\u5bfc\u51fa\u4e0e\u5206\u4eab</h1>');
add('    </header>');
add('    <div class="export-container">');
add('      <div class="export-section">');
add('        <h3>\ud83d\udce4 \u5bfc\u51fa\u9009\u9879</h3>');
add('        <div class="export-options">');
add('          <button class="export-btn" id="export-pdf"><span class="export-icon">\ud83d\udcd1</span><span class="export-text">\u5bfc\u51fa\u5b8c\u6574\u7b56\u5212 PDF</span></button>');
add('          <button class="export-btn" id="export-word"><span class="export-icon">\ud83d\udcdd</span><span class="export-text">\u5bfc\u51fa\u4e32\u8bcd Word \u6587\u6863</span></button>');
add('          <button class="export-btn" id="export-text"><span class="export-icon">\ud83d\udccb</span><span class="export-text">\u590d\u5236\u6d3b\u52a8\u65b9\u6848\u6458\u8981\u6587\u672c</span></button>');
add('        </div>');
add('      </div>');
add('      <div class="export-section">');
add('        <h3>\ud83d\udd17 \u5206\u4eab\u9009\u9879</h3>');
add('        <div class="export-options">');
add('          <button class="export-btn" id="share-poster"><span class="export-icon">\ud83d\uddbc\ufe0f</span><span class="export-text">\u751f\u6210\u5206\u4eab\u6d77\u62a5</span></button>');
add('          <button class="export-btn" id="share-link"><span class="export-icon">\ud83d\udd17</span><span class="export-text">\u5206\u4eab\u94fe\u63a5</span></button>');
add('        </div>');
add('      </div>');
add('      <div class="export-section poster-bg-section">');
add('        <h3>\ud83c\udfa8 \u6d77\u62a5\u80cc\u666f\u8bbe\u7f6e</h3>');
add('        <p class="section-hint">\u9009\u62e9\u80cc\u666f\u540e\u70b9\u51fb\u300c\u751f\u6210\u5206\u4eab\u6d77\u62a5\u300d</p>');
add('        <div class="bg-preset-row">');
add('          <div class="bg-preset active" data-preset="default"><div class="bg-preset-thumb bg-preset-default"></div><span>\u9ed8\u8ba4\u7eff</span></div>');
add('          <div class="bg-preset" data-preset="night"><div class="bg-preset-thumb bg-preset-night"></div><span>\u661f\u7a7a\u591c</span></div>');
add('          <div class="bg-preset" data-preset="sunset"><div class="bg-preset-thumb bg-preset-sunset"></div><span>\u65e5\u843d\u6a59</span></div>');
add('          <div class="bg-preset" data-preset="ocean"><div class="bg-preset-thumb bg-preset-ocean"></div><span>\u6d77\u6d0b\u84dd</span></div>');
add('          <div class="bg-preset" data-preset="custom"><div class="bg-preset-thumb bg-preset-custom"><span class="upload-plus">\uff0b</span></div><span>\u81ea\u5b9a\u4e49</span></div>');
add('        </div>');
add('        <div id="custom-upload-area" class="custom-upload-area" style="display:none;">');
add('          <label for="background-upload" class="upload-label">');
add('            <div class="upload-drop-zone" id="upload-drop-zone">');
add('              <span class="upload-icon-big">\ud83d\uddbc\ufe0f</span>');
add('              <p>\u70b9\u51fb\u6216\u62d6\u62fd\u56fe\u7247\u5230\u6b64\u5904</p>');
add('              <p class="upload-hint">\u652f\u6301 JPG / PNG / WebP</p>');
add('            </div>');
add('          </label>');
add('          <input type="file" id="background-upload" accept="image/jpeg,image/png,image/webp" style="display:none;">');
add('        </div>');
add('        <div id="background-preview" class="bg-preview-wrap" style="display:none;">');
add('          <img id="background-image-preview" src="" alt="\u80cc\u666f\u9884\u89c8">');
add('          <div class="bg-preview-actions">');
add('            <span id="background-filename" class="bg-filename"></span>');
add('            <button class="btn-remove-bg" id="btn-remove-bg">\u2715 \u79fb\u9664</button>');
add('          </div>');
add('        </div>');
add('      </div>');
add('      <button class="btn-secondary btn-full" id="btn-view-history"><span>\ud83d\udcda</span> \u67e5\u770b\u5386\u53f2\u65b9\u6848\u8bb0\u5f55</button>');
add('      <button class="btn-primary btn-full" id="btn-new-plan"><span>\ud83d\udd04</span> \u91cd\u65b0\u7b56\u5212\u4e00\u4e2a\u6d3b\u52a8</button>');
add('    </div>');
add('  </div>');
add('');
add('  <!-- Page 5: \u5386\u53f2\u8bb0\u5f55\u9875 (P3) -->');
add('  <div id="page-history" class="page">');
add('    <header class="export-header">');
add('      <button class="btn-back" id="btn-back-history"><span>\u2190</span> \u8fd4\u56de</button>');
add('      <h1>\u5386\u53f2\u65b9\u6848\u8bb0\u5f55</h1>');
add('    </header>');
add('    <div class="export-container">');
add('      <div class="history-list" id="history-list"></div>');
add('    </div>');
add('  </div>');
add('');
add('  <!-- Page 6: \u6d3b\u52a8\u56de\u987e\u9875 (v2.0\u65b0\u589e) -->');
add('  <div id="page-review" class="page">');
add('    <header class="result-header">');
add('      <button class="btn-back" id="btn-back-review"><span>\u2190</span> \u8fd4\u56de\u65b9\u6848</button>');
add('      <h1 class="result-title">\u6d3b\u52a8\u56de\u987e</h1>');
add('    </header>');
add('    <div class="review-container">');
add('');
add('      <!-- \u2460 \u6d3b\u52a8\u4fe1\u606f\u5c55\u793a\u533a -->');
add('      <div class="review-section review-info-section">');
add('        <div class="review-activity-info" id="review-activity-info">');
add('          <span class="review-activity-name" id="review-name">\u6d3b\u52a8\u540d\u79f0</span>');
add('          <div class="review-activity-meta">');
add('            <span id="review-meta-date">\ud83d\udcc5 --</span>');
add('            <span id="review-meta-people">\ud83d\udc65 --</span>');
add('          </div>');
add('        </div>');
add('      </div>');
add('');
add('      <!-- \u2461 \u7d20\u6750\u4e0a\u4f20\u533a -->');
add('      <div class="review-section">');
add('        <div class="review-section-header">');
add('          <h3>\ud83d\udcf8 \u4e0a\u4f20\u6d3b\u52a8\u7d20\u6750</h3>');
add('          <span class="review-count-badge" id="media-count">0 \u4e2a\u6587\u4ef6</span>');
add('        </div>');
add('        <div class="review-upload-zone" id="review-upload-zone">');
add('          <label for="media-upload" class="review-upload-label">');
add('            <span class="review-upload-icon">\uff0b</span>');
add('            <p>\u70b9\u51fb\u4e0a\u4f20\u7167\u7247 / \u89c6\u9891\u7247\u6bb5</p>');
add('            <p class="upload-hint">\u652f\u6301 JPG / PNG / MP4</p>');
add('          </label>');
add('          <input type="file" id="media-upload" accept="image/*,video/mp4" multiple style="display:none;">');
add('        </div>');
add('        <div class="media-preview-grid" id="media-preview-grid"></div>');
add('      </div>');
add('');
add('      <!-- \u2462 \u6d3b\u52a8\u611f\u60f3\u8f93\u5165\u533a -->');
add('      <div class="review-section">');
add('        <div class="review-section-header">');
add('          <h3>\ud83d\udcac \u6d3b\u52a8\u611f\u60f3</h3>');
add('          <span class="review-optional">\u9009\u586b \u00b7 AI\u5c06\u8f6c\u4e3a\u89c6\u9891\u5b57\u5e55</span>');
add('        </div>');
add('        <textarea id="review-caption" class="review-textarea" rows="3" placeholder="\u5199\u4e0b\u8fd9\u6b21\u6d3b\u52a8\u7684\u7cbe\u5f69\u77ac\u95f4\u3001\u611f\u60f3\u6216\u5bc4\u8bed..."></textarea>');
add('      </div>');
add('');
add('      <!-- \u2463 \u56de\u987e\u89c6\u9891\u914d\u4e50\u533a -->');
add('      <div class="review-section">');
add('        <div class="review-section-header">');
add('          <h3>\ud83c\udfb5 \u56de\u987e\u89c6\u9891\u914d\u4e50</h3>');
add('          <button class="btn-change-bgm" id="btn-change-bgm">\ud83d\udd00 \u6362\u4e00\u9996</button>');
add('        </div>');
add('        <div class="review-bgm-card" id="review-bgm-card">');
add('          <span class="review-bgm-cover">\ud83c\udfb5</span>');
add('          <div class="review-bgm-info">');
add('            <div class="review-bgm-title" id="review-bgm-title">\u81ea\u52a8\u5339\u914d\u4e2d...</div>');
add('            <div class="review-bgm-artist" id="review-bgm-artist">\u6765\u81ea QQ\u97f3\u4e50</div>');
add('          </div>');
add('          <span class="review-bgm-playing">\u25b6</span>');
add('        </div>');
add('      </div>');
add('');
add('      <!-- \u2464 AI\u751f\u6210\u56de\u987e\u89c6\u9891\u6309\u94ae -->');
add('      <div class="review-section">');
add('        <div class="review-section-header">');
add('          <h3>\ud83e\udd16 AI\u751f\u6210\u56de\u987e\u89c6\u9891</h3>');
add('          <span class="review-optional">\u667a\u80fd\u526a\u8f91 + \u5b57\u5e55 + \u914d\u4e50</span>');
add('        </div>');
add('        <div class="gen-option-row">');
add('          <span class="gen-option-label">\u89c6\u9891\u98ce\u683c</span>');
add('          <div class="gen-option-chips" id="review-video-style">');
add('            <button class="chip active" data-value="\u6e29\u60c5">\ud83d\udc9d \u6e29\u60c5</button>');
add('            <button class="chip" data-value="\u6d3b\u6cfc">\ud83c\udf89 \u6d3b\u6cfc</button>');
add('            <button class="chip" data-value="\u71c3">\ud83d\udd25 \u71c3</button>');
add('            <button class="chip" data-value="\u6587\u827a">\ud83c\udfa8 \u6587\u827a</button>');
add('          </div>');
add('        </div>');
add('        <button class="btn-gen-review" id="btn-gen-review">');
add('          <span>\ud83c\udfac</span> AI \u751f\u6210\u56de\u987e\u89c6\u9891');
add('        </button>');
add('      </div>');
add('');
add('      <!-- \u2465 \u89c6\u9891\u9884\u89c8\u533a -->');
add('      <div class="review-section" id="review-preview-section" style="display:none">');
add('        <div class="review-section-header">');
add('          <h3>\u25b6 \u89c6\u9891\u9884\u89c8</h3>');
add('          <button class="btn-change-bgm" id="btn-regen-review">\ud83d\udd04 \u91cd\u65b0\u751f\u6210</button>');
add('        </div>');
add('        <div class="review-video-player">');
add('          <div class="review-video-screen" id="review-video-screen">');
add('            <div class="video-thumb">');
add('              <span class="video-play-btn">\u25b6</span>');
add('              <div class="video-overlay-text" id="video-overlay-text"></div>');
add('            </div>');
add('          </div>');
add('          <div class="video-controls">');
add('            <span class="vc-time">0:00 / 2:30</span>');
add('            <div class="vc-progress"><div class="vc-bar" id="vc-bar"></div></div>');
add('            <span class="vc-vol">\ud83d\udd0a</span>');
add('          </div>');
add('        </div>');
add('      </div>');
add('');
add('      <!-- \u2466 \u53d1\u5e03\u4e0e\u5206\u4eab\u533a -->');
add('      <div class="review-section" id="review-publish-section" style="display:none">');
add('        <div class="review-section-header">');
add('          <h3>\ud83d\ude80 \u53d1\u5e03\u4e0e\u5206\u4eab</h3>');
add('        </div>');
add('        <div class="review-publish-actions">');
add('          <button class="btn-review-publish" id="btn-publish-review"><span>\ud83d\udcfa</span> \u4e00\u952e\u53d1\u5e03\u5230\u817e\u8baf\u89c6\u9891</button>');
add('          <button class="btn-review-share-qq" id="btn-review-share-qq"><span>\ud83d\udcac</span> \u5206\u4eab\u5230 QQ \u7fa4</button>');
add('          <button class="btn-review-share-wx" id="btn-review-share-wx"><span>\ud83d\udc9a</span> \u5206\u4eab\u5230\u5fae\u4fe1</button>');
add('        </div>');
add('      </div>');
add('');
add('    </div>');
add('  </div>');
add('');
add('  <script src="js/mock-data.js"></script>');
add('  <script src="js/app.js"></script>');
add('  <script src="js/history.js"></script>');
add('  <script src="js/trailer.js"></script>');
add('  <script src="js/review.js"></script>');
add('</body>');
add('</html>');
fs.writeFileSync(p, lines.join('\n'), {encoding:'utf8'});
console.log('OK lines=' + lines.length);

